package entities;
// Generated Nov 7, 2017 10:33:36 PM by Hibernate Tools 4.3.1



/**
 * Chitiethd generated by hbm2java
 */
public class Chitiethd  implements java.io.Serializable {


     private int maCt;
     private Donhang donhang;
     private Sanpham sanpham;
     private Integer soluong;
     private Float tongtien;
     private Float thanhtien;

    public Chitiethd() {
    }

	
    public Chitiethd(int maCt, Donhang donhang, Sanpham sanpham) {
        this.maCt = maCt;
        this.donhang = donhang;
        this.sanpham = sanpham;
    }
    public Chitiethd(int maCt, Donhang donhang, Sanpham sanpham, Integer soluong, Float tongtien, Float thanhtien) {
       this.maCt = maCt;
       this.donhang = donhang;
       this.sanpham = sanpham;
       this.soluong = soluong;
       this.tongtien = tongtien;
       this.thanhtien = thanhtien;
    }
   
    public int getMaCt() {
        return this.maCt;
    }
    
    public void setMaCt(int maCt) {
        this.maCt = maCt;
    }
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Float getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Float tongtien) {
        this.tongtien = tongtien;
    }
    public Float getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(Float thanhtien) {
        this.thanhtien = thanhtien;
    }




}


