package entities;
// Generated Nov 7, 2017 10:33:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Quyen generated by hbm2java
 */
public class Quyen  implements java.io.Serializable {


     private int maQ;
     private String tenquyen;
     private Set taikhoans = new HashSet(0);

    public Quyen() {
    }

	
    public Quyen(int maQ) {
        this.maQ = maQ;
    }
    public Quyen(int maQ, String tenquyen, Set taikhoans) {
       this.maQ = maQ;
       this.tenquyen = tenquyen;
       this.taikhoans = taikhoans;
    }
   
    public int getMaQ() {
        return this.maQ;
    }
    
    public void setMaQ(int maQ) {
        this.maQ = maQ;
    }
    public String getTenquyen() {
        return this.tenquyen;
    }
    
    public void setTenquyen(String tenquyen) {
        this.tenquyen = tenquyen;
    }
    public Set getTaikhoans() {
        return this.taikhoans;
    }
    
    public void setTaikhoans(Set taikhoans) {
        this.taikhoans = taikhoans;
    }




}


