package pojo;
// Generated Dec 2, 2017 3:44:02 AM by Hibernate Tools 4.3.1



/**
 * Lienhe generated by hbm2java
 */
public class Lienhe  implements java.io.Serializable {


     private Integer maLh;
     private Trangthai trangthai;
     private String hoten;

    public String getHoten() {
        return hoten;
    }

    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    public String getSodienthoai() {
        return sodienthoai;
    }

    public void setSodienthoai(String sodienthoai) {
        this.sodienthoai = sodienthoai;
    }
     private String email;
     private String sodienthoai;
     private String lienhe;

    public Lienhe() {
    }

	
    public Lienhe(String email) {
        this.email = email;
    }
    public Lienhe( String hoten,String email, String sodienthoai,String lienhe) {
       this.hoten=hoten;
       this.email = email;
       this.sodienthoai=sodienthoai;
       this.lienhe = lienhe;
    }
    public Lienhe(Trangthai trangthai, String hoten,String email, String sodienthoai,String lienhe) {
       this.trangthai = trangthai;
       this.hoten=hoten;
       this.email = email;
       this.sodienthoai=sodienthoai;
       this.lienhe = lienhe;
    }
   
    public Integer getMaLh() {
        return this.maLh;
    }
    
    public void setMaLh(Integer maLh) {
        this.maLh = maLh;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLienhe() {
        return this.lienhe;
    }
    
    public void setLienhe(String lienhe) {
        this.lienhe = lienhe;
    }




}


