package pojo;
// Generated Dec 2, 2017 3:44:02 AM by Hibernate Tools 4.3.1



/**
 * Lienhe generated by hbm2java
 */
public class Lienhe  implements java.io.Serializable {


     private Integer maLh;
     private Trangthai trangthai;
     private String email;
     private String lienhe;

    public Lienhe() {
    }

	
    public Lienhe(String email) {
        this.email = email;
    }
    public Lienhe(Trangthai trangthai, String email, String lienhe) {
       this.trangthai = trangthai;
       this.email = email;
       this.lienhe = lienhe;
    }
   
    public Integer getMaLh() {
        return this.maLh;
    }
    
    public void setMaLh(Integer maLh) {
        this.maLh = maLh;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLienhe() {
        return this.lienhe;
    }
    
    public void setLienhe(String lienhe) {
        this.lienhe = lienhe;
    }




}


